### ISSUE TITLE
Problem running tests on Linux

### ISSUE THREAD

**Issue by asiviero** [Shopify/shopify_python_api#109]
I have tried to run the test suite in a Linux environment, however I came across something in one of the `base_test.py` tests. I suspect it has something to do with the `mock` module. I have installed it following the instructions in the readme:

```
    git clone git@github.com:asiviero/shopify_python_api.git
    python setup.py sdist
    pip install --upgrade dist/ShopifyAPI-*.tar.gz
```

Then I ran `$ python setup.py test` and the output was:

```
running test
Searching for six>=1.7
Best match: six 1.9.0

Using /usr/local/lib/python2.7/dist-packages
running egg_info
writing requirements to ShopifyAPI.egg-info/requires.txt
writing ShopifyAPI.egg-info/PKG-INFO
writing top-level names to ShopifyAPI.egg-info/top_level.txt
writing dependency_links to ShopifyAPI.egg-info/dependency_links.txt
writing pbr to ShopifyAPI.egg-info/pbr.json
reading manifest file 'ShopifyAPI.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'ShopifyAPI.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 44, in <module>
    'Topic :: Software Development :: Libraries :: Python Modules']
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/test.py", line 135, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/test.py", line 116, in with_project_on_sys_path
    func()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/test.py", line 160, in run_tests
    testLoader = cks
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 103, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/test.py", line 36, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'base_test'
```

After some trial and error, I have removed `from mock import patch` and `test_delete_should_send_custom_headers_with_request`, and all tests passed:

```
----------------------------------------------------------------------
Ran 98 tests in 0.114s

OK
```

Am I missing something? Maybe a requirement missing or something like that?

**Comment by kevinhughes27** [comment]
Travis runs the test suite just fine so it must be a package on your system that it doesn't like. If you cant find a fix that involves fixing that test I will happily accept it

**Comment by asiviero** [comment]
It was indeed a packages issue. Some mess with python2 and 3 in the same machine or something like that. I have fixed it up at my machine to run the tests.
