### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'encode' on hmac verification

### ISSUE THREAD

**Issue by altunyurt** [Shopify/shopify_python_api#165]
Following code throws the exception below from time to time. 

```
def get_token(data):
    token = shopify.Session(data.get('domain')).request_token({
        'code': data.get('code'),
        'shop': data.get('domain'),
        'timestamp': data.get('timestamp'),
        'hmac': data.get('hmac')
    })
```

```
GET /auth/callback?code=51b462ff1de0705f5685ff36ec3a2aea&hmac=cdeb894206488d3a89d458003125779f94a1a7b02158932097c801f43fd043b5&shop=denemestore-7.myshopify.com&timestamp=1476806408

Traceback (most recent call last):
  File "/home/altunyurt/calisma/cbslab/shop/shopify/sfy/views/auth.py", line 122, in auth_callback
    shop_token = shoplib.get_token(dict({'domain': domain}, **request.args.to_dict()))
  File "/home/altunyurt/calisma/cbslab/shop/shopify/sfy/lib/shopify.py", line 15, in get_token
    'hmac': data.get('hmac')
  File "/home/altunyurt/calisma/genel/shopify/local/lib/python2.7/site-packages/shopify/session.py", line 55, in request_token
    if not self.validate_params(params):
  File "/home/altunyurt/calisma/genel/shopify/local/lib/python2.7/site-packages/shopify/session.py", line 105, in validate_params
    return cls.validate_hmac(params)
  File "/home/altunyurt/calisma/genel/shopify/local/lib/python2.7/site-packages/shopify/session.py", line 112, in validate_hmac
    hmac_calculated = cls.calculate_hmac(params).encode('utf-8')
  File "/home/altunyurt/calisma/genel/shopify/local/lib/python2.7/site-packages/shopify/session.py", line 131, in calculate_hmac
    return hmac.new(cls.secret.encode(), encoded_params.encode(), sha256).hexdigest()
AttributeError: 'NoneType' object has no attribute 'encode'
```

It mostly happens when i click on my app's link in admin interface right after i restart my application server. Apparently the first oauth redirect seems to be failing most of the time

**Comment by chrisxwan** [comment]
@altunyurt I'm experiencing the same problem -- were you ever able to find a fix for this?

**Comment by altunyurt** [comment]
@chrisxwan i just try-catch it and re-redirect user to shopify oauth. It just takes a fraction of users time, which is very negligable and works smoothly.

**Comment by pbojinov** [comment]
I started noticing this on occasion as well.

```python
self.token = session.request_token(params)
File "/opt/python/run/venv/lib/python2.7/site-packages/shopify/session.py", line 55, in request_token
if not self.validate_params(params):
File "/opt/python/run/venv/lib/python2.7/site-packages/shopify/session.py", line 105, in validate_params
return cls.validate_hmac(params)
File "/opt/python/run/venv/lib/python2.7/site-packages/shopify/session.py", line 112, in validate_hmac
hmac_calculated = cls.calculate_hmac(params).encode('utf-8')
File "/opt/python/run/venv/lib/python2.7/site-packages/shopify/session.py", line 130, in calculate_hmac
return hmac.new(cls.secret.encode(), encoded_params.encode(), sha256).hexdigest()
AttributeError: 'NoneType' object has no attribute 'encode'
```

**Comment by pbojinov** [comment]
Anyone have thoughts on what's causing this?

**Comment by travis-shippingtree** [comment]
The secret appears to be null. 
Make sure you're calling this:

shopify.Session.setup(api_key=API_KEY, secret=SHARED_SECRET)
