### ISSUE TITLE
shopify_api.py under Python 3.5 - NameError: name 'raw_input' is not defined

### ISSUE THREAD

**Issue by dvska** [Shopify/shopify_python_api#172]
`$ python shopify_api.py add myshop`

```
Traceback (most recent call last):
  File "/shopify_api.py", line 248, in <module>
    Tasks.run_task(*sys.argv[1:])
  File "/shopify_api.py", line 58, in run_task
    task_func(*args)
  File "/shopify_api.py", line 110, in add
    domain = raw_input("Domain? (leave blank for %s.myshopify.com) " % (connection))
NameError: name 'raw_input' is not defined
```

**Comment by jamiemtdwyer** [comment]
Closed by https://github.com/Shopify/shopify_python_api/pull/268.
