### ISSUE TITLE
v5.0.0 has broken private app authentication

### ISSUE THREAD

**Issue by monokal** [Shopify/shopify_python_api#313]
The following was working fine until the release of v5.0.0. According to the README, this should not have been affected:

Code (still valid according to this repo's README):
```python
        try:
            shop_url = f"https://{api_key}:{api_pass}@{shop_name}.myshopify.com/admin"

            self.log(f"Connecting to \"{shop_name}\" shop...", 'info')
            shopify.ShopifyResource.set_site(shop_url)

        except Exception as e:
            self.log("Error while connecting to shop:\n{}".format(e), 'exception')
            sys.exit(1)
```

```python
listed_products = []

        page_no = 1
        has_pages = True
        try:
            while has_pages:
                self.log("Retrieving listings (page: {})...".format(page_no), 'info')
                page = shopify.Product.find(limit=250, page=page_no)

                if page:
                    listed_products.extend(page)
                    page_no += 1

                else:
                    has_pages = False

        except Exception as e:
            self.log("Error while retrieving listed products:\n{}".format(e), 'exception')
            sys.exit(1)

        return listed_products
```

Traceback:
```
INFO > Retrieving listings (page: 1)...
EXCEPTION > Error while retrieving listed products:
type object 'ShopifyResource' has no attribute '_url'
Traceback (most recent call last):
  File "./market/shopify/market.py", line 54, in get_listed_products
  File "/usr/local/lib/python3.7/site-packages/pyactiveresource/activeresource.py", line 385, in find
    return cls._find_every(from_=from_, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyactiveresource/activeresource.py", line 523, in _find_every
    return cls._build_list(cls.connection.get(path, cls.headers),
  File "/usr/local/lib/python3.7/site-packages/shopify/base.py", line 45, in connection
    local.url = cls.url
  File "/usr/local/lib/python3.7/site-packages/shopify/base.py", line 154, in get_url
    return getattr(cls._threadlocal, 'url', ShopifyResource._url)
AttributeError: type object 'ShopifyResource' has no attribute '_url'
```

**Comment by monokal** [comment]
https://github.com/Shopify/shopify_python_api/pull/312
