### ISSUE TITLE
ValueError: invalid literal for int() with base 16: b'' during shopify.Order.find(...) call

### ISSUE THREAD

**Issue by ascheucher** [Shopify/shopify_python_api#320]
During a paging call on shopify.Order.find(...) I get following stacktrace:

```
IncompleteRead(877911 bytes read)
Traceback (most recent call last):
 File "/usr/local/lib/python3.7/http/client.py", line 544, in _get_chunk_left
   chunk_left = self._read_next_chunk_size()
 File "/usr/local/lib/python3.7/http/client.py", line 511, in _read_next_chunk_size
   return int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/usr/local/lib/python3.7/http/client.py", line 561, in _readall_chunked
   chunk_left = self._get_chunk_left()
 File "/usr/local/lib/python3.7/http/client.py", line 546, in _get_chunk_left
   raise IncompleteRead(b'')
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "design_db/04_shopify_scripts/10-handle-orders-with-anomalies.py", line 87, in main
   shopify.Order.find, limit=100, page=page, fulfillment_status='unshipped,partial')
 File "/app/design_db/modules/otaya/shopify/commons.py", line 441, in call_shopify_api_with_retry
   return active_resource_function(*args, **kwargs)
 File "/usr/local/lib/python3.7/site-packages/pyactiveresource/activeresource.py", line 385, in find
   return cls._find_every(from_=from_, **kwargs)
 File "/usr/local/lib/python3.7/site-packages/pyactiveresource/activeresource.py", line 523, in _find_every
   return cls._build_list(cls.connection.get(path, cls.headers),
 File "/usr/local/lib/python3.7/site-packages/pyactiveresource/connection.py", line 329, in get
   return self.format.decode(self._open('GET', path, headers=headers).body)
 File "/usr/local/lib/python3.7/site-packages/shopify/base.py", line 23, in _open
   self.response = super(ShopifyConnection, self)._open(*args, **kwargs)
 File "/usr/local/lib/python3.7/site-packages/pyactiveresource/connection.py", line 291, in _open
   response = Response.from_httpresponse(http_response)
 File "/usr/local/lib/python3.7/site-packages/pyactiveresource/connection.py", line 184, in from_httpresponse
   return cls(response.code, response.read(),
 File "/usr/local/lib/python3.7/http/client.py", line 454, in read
   return self._readall_chunked()
 File "/usr/local/lib/python3.7/http/client.py", line 568, in _readall_chunked
   raise IncompleteRead(b''.join(value))
http.client.IncompleteRead: IncompleteRead(877911 bytes read)
```

This looks like the response from the REST endpoint is malformed sometimes.

**Comment by timrichardson** [comment]
I'm getting a similar error. 
 ValueError: invalid literal for int() with base 10: 'f7f00e73041 ... @cultivergoods.myshopify.com'

It's from here:
/usr/local/lib/python3.7/http/client.py:887: ValueError

    def _get_hostport(self, host, port):
        if port is None:
            i = host.rfind(':')
            j = host.rfind(']')         # ipv6 addresses have [...]
            if i > j:
                try:
>                   port = int(host[i+1:])
E                   ValueError: invalid literal for int() with base 10: 'f7f00e7304...@cultivergoods.myshopify.com'
