### ISSUE TITLE
Periodic pyactiveresource.connection.ServerError with shopify.Product.find

### ISSUE THREAD

**Issue by fkpvw** [Shopify/shopify_python_api#344]
I am using the following loop to get all products from a particular collection. Sometimes I get pyactiveresource.connection.ServerError for a particular user but not always. The number of loops before this error occurs also differ every time. 

It seems to be different from the 'Too Many Requests' error which can be managed by changing the duration between calls as well. Any ideas? Thanks!

    while len(query_products) == 250:
        query_products = shopify.Product.find(
            fields='id, title, tags, admin_graphql_api_id',
            collection_id=collection_id,
            limit=250,
            since_id=products[-1].id
        )
        products.extend(query_products)

**Comment by tanema** [comment]
Do you have more information from the error? Do you have any more information about this error?

**Comment by fkpvw** [comment]
This is the entire traceback, not sure if it is helpful. And it seems to only happen for one particular shop.

```
Traceback (most recent call last):
  File "/opt/advanced-custom-collections/app/venv/lib/python3.6/site-packages/pyactiveresource/connection.py", line 286, in _open
    http_response = self._handle_error(self._urlopen(request))
  File "/opt/advanced-custom-collections/app/venv/lib/python3.6/site-packages/pyactiveresource/connection.py", line 316, in _urlopen
    return urllib.request.urlopen(request, timeout=self.timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/advanced-custom-collections/app/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/advanced-custom-collections/app/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/advanced-custom-collections/app/venv/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/advanced-custom-collections/app/venv/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/opt/advanced-custom-collections/app/api/management/commands/debug.py", line 21, in handle
    p = get_shopify_products_by_collection_id(associated_shopify_collection.shopify_id)
  File "/opt/advanced-custom-collections/app/api/views.py", line 593, in get_shopify_products_by_collection_id
    since_id=products[-1].id
  File "/opt/advanced-custom-collections/app/venv/lib/python3.6/site-packages/pyactiveresource/activeresource.py", line 385, in find
    return cls._find_every(from_=from_, **kwargs)
  File "/opt/advanced-custom-collections/app/venv/lib/python3.6/site-packages/pyactiveresource/activeresource.py", line 523, in _find_every
    return cls._build_list(cls.connection.get(path, cls.headers),
  File "/opt/advanced-custom-collections/app/venv/lib/python3.6/site-packages/pyactiveresource/connection.py", line 329, in get
    return self.format.decode(self._open('GET', path, headers=headers).body)
  File "/opt/advanced-custom-collections/app/venv/lib/python3.6/site-packages/shopify/base.py", line 23, in _open
    self.response = super(ShopifyConnection, self)._open(*args, **kwargs)
  File "/opt/advanced-custom-collections/app/venv/lib/python3.6/site-packages/pyactiveresource/connection.py", line 288, in _open
    http_response = self._handle_error(err)
  File "/opt/advanced-custom-collections/app/venv/lib/python3.6/site-packages/pyactiveresource/connection.py", line 418, in _handle_error
    raise ServerError(err)
pyactiveresource.connection.ServerError: Internal Server Error

```

**Comment by tanema** [comment]
Has this happened more than just today? Because that error indicates an error from shopify's API

**Comment by fkpvw** [comment]
Yes more than just today, our user was emailing us about an issue they have with our app the past three weeks or so. We tried different things and we just managed to narrow down to this as it is only happening sporadically.

So we began testing just this function and found that sometimes it completes and we get all the products, but sometimes this error occurs at different loop runs.

**Comment by tanema** [comment]
What is your app? Is it published? You should probably contact support about that if it is a public app

**Comment by fkpvw** [comment]
Yes it is published / public. Thanks, let me contact support then.
