### ISSUE TITLE
Getting `urllib.error.HTTPError: HTTP Error 500: Internal Server Error` when saving an order

### ISSUE THREAD

**Issue by rvarbanov** [Shopify/shopify_python_api#349]
I'm getting an intermittent errors (`urllib.error.HTTPError: HTTP Error 500: Internal Server Error` & `pyactiveresource.connection.ServerError: Internal Server`), when trying to save a new order. I'm using `ShopifyAPI==3.1.0`

Here is the traceback that I'm seeing in the logs:
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pyactiveresource/connection.py", line 286, in _open
    http_response = self._handle_error(self._urlopen(request))
  File "/usr/local/lib/python3.6/dist-packages/pyactiveresource/connection.py", line 316, in _urlopen
    return urllib.request.urlopen(request, timeout=self.timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/var/www/html/shopifyapp/util.py", line 252, in create_shopify_order
    order.save()
  File "/usr/local/lib/python3.6/dist-packages/pyactiveresource/activeresource.py", line 824, in save
    data=self.encode())
  File "/usr/local/lib/python3.6/dist-packages/pyactiveresource/connection.py", line 364, in post
    return self._open('POST', path, headers=headers, data=data)
  File "/usr/local/lib/python3.6/dist-packages/shopify/base.py", line 23, in _open
    self.response = super(ShopifyConnection, self)._open(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pyactiveresource/connection.py", line 288, in _open
    http_response = self._handle_error(err)
  File "/usr/local/lib/python3.6/dist-packages/pyactiveresource/connection.py", line 418, in _handle_error
    raise ServerError(err)
pyactiveresource.connection.ServerError: Internal Server Error
```

**Comment by ruslan287** [comment]
Have the same issue. I try to update resource to 5.1.2 with api version 2019-04, same issue

**Comment by tanema** [comment]
@ruslan287 I would recommend reaching out to support. If Shopify is throwing 500 errors then it is an API problem. Support will be able to analyze your app and search our logs for the issue
