### ISSUE TITLE
AttributeError: product - when I want to create and save a Product

### ISSUE THREAD

**Issue by jerkkao** [Shopify/shopify_python_api#404]
I found an issue when I want to do some basic Product creation which is from the sample code.
I think it's caused by the code in `/resources/product.py, line 39` when it checks there is any variant in the product or not.
`if 'variants' in self.product.attributes:`

With Python 3.7.5
```Python
def main():
  # with the right API_KEY, PASSWORD, SHOP_NAME, API_VERSION
  shop_url = "https://%s:%s@%s.myshopify.com/admin/api/%s" % (API_KEY, PASSWORD, SHOP_NAME, API_VERSION)
  shopify.ShopifyResource.set_site(shop_url)

  product = shopify.Product()
  product.title = "Shopify test title"
  saved_successfully = product.save()

if __name__ == '__main__':
  main()
```

Output with call stack
```Shell
Traceback (most recent call last):
  File "main.py", line 51, in <module>
    main()
  File "main.py", line 42, in main
    saved_successfully = product.save()
  File "/usr/local/lib/python3.7/site-packages/shopify/resources/product.py", line 39, in save
    if 'variants' in self.product.attributes:
  File "/usr/local/lib/python3.7/site-packages/pyactiveresource/activeresource.py", line 917, in __getattr__
    raise AttributeError(name)
AttributeError: product
```

Thanks,

**Comment by smubbs** [comment]
#386 Similar issue here

**Comment by asfakianos** [comment]
I fixed this and submitted a pull request (#403). If you want to fix it manually, you can change `if 'variants' in self.product.attributes:` to `if 'variants' in self.attributes:` in shopify/resources/product.py.
