### ISSUE TITLE
VersionNotFoundError while create a session 

### ISSUE THREAD

**Issue by sreejithavg** [Shopify/shopify_python_api#443]
# Issue summary
ERROR:django.request:Internal Server Error: /shopify/login/finalize/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yfret/cemantica/cemantica/notfw/event_ws/shopifyhandler/shopify_authentication.py", line 125, in finalize
    shopify_session = shopify.Session(shopify_shop, consts.SHOPIFY_API_VERSION, token=request.GET.get('token'))
  File "/home/yfret/.local/lib/python2.7/site-packages/shopify/session.py", line 47, in __init__
    self.version = ApiVersion.coerce_to_version(version)
  File "/home/yfret/.local/lib/python2.7/site-packages/shopify/api_version.py", line 18, in coerce_to_version
    raise VersionNotFoundError
VersionNotFoundError

Write a short description of the issue here ↓
tried authenticate by creating new session with 
shopify_session = shopify.Session(shopify_shop, consts.SHOPIFY_API_VERSION, token=request.GET.get('token'))
here
consts.SHOPIFY_API_VERSION = '2020-10'
## Expected behavior

no error

## Actual behavior
500 VersionNotFoundError

## Specifications

- `shopify_python_api` version: 8.1.0
- `pyactiveresource` version: 2.2.1
- Shopify API version used :'2020-10'

**Comment by mllemango** [comment]
Hey @sreejithavg, it looks like the api version is never passed into `shopify.Session()`. Could you double check that `consts.SHOPIFY_API_VERSION` returns the expected string on the line before you create the new session?

**Comment by sreejithavg** [comment]
I tried as below, still has the issue

shopify_session = shopify.Session(shopify_shop, '2020-10', token=request.GET.get('token'))

**Comment by mllemango** [comment]
Interesting, in October we had a PR that actually removed '2019-10' and added '2020-10' https://github.com/Shopify/shopify_python_api/pull/416. Could you try updating the package?

**Comment by mllemango** [comment]
If that doesn't work, a manual check in `/home/yfret/.local/lib/python2.7/site-packages/shopify/api_version.py` would determine what packages are defined under the method `define_known_versions(cls)`.
