### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by hongfeizhou** [Shopify/shopify_python_api#480]
code:
shopify.Order().find(limit=100)
error:
 
 File "*/shopify/pyactiveresource/activeresource.py", line 383, in find
    return cls._find_every(from_=from_, **kwargs)
  File "*/shopify/pyactiveresource/activeresource.py", line 513, in _find_every
    prefix_options, query_options = cls._split_options(kwargs)
  File "*/shopify/pyactiveresource/activeresource.py", line 464, in _split_options
    if key in cls._prefix_parameters():
  File "*/shopify/pyactiveresource/activeresource.py", line 732, in _prefix_parameters
    for match in template.pattern.finditer(path):
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: expected string or bytes-like object

**Comment by hongfeizhou** [comment]
i just use the find method , but it does not work

**Comment by kamlesh538** [comment]
That's a big hint. Solved my problem. Thanks @deejax
