### ISSUE TITLE
Unclear error when trying to create discount code

### ISSUE THREAD

**Issue by nonfatalexec** [Shopify/shopify_python_api#501]
# Issue summary

Write a short description of the issue here ↓
I'm trying to create a discount code with this snippet of code.
```python
price_rule = shopify.PriceRule.create({
    "price_rule_id" : 11111,
    "title" : "5_OFF_85_000001",
    "target_type" : "line_item",
    "target_selection" : "entitled",
    "allocation_method" : "across",
    "value_type" : "fixed_amount",
    "value" : "-5",
    "once_per_customer" : True,
    "prerequisite_subtotal_range" : {"greater_than_or_equal_to" : "85.0"},
    "customer_selection" : "all",
    "starts_at" : datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    "ends_at" : (datetime.today() + timedelta(days=5)).strftime("%Y-%m-%d %H:%M:%S")
    })

discount_code = shopify.DiscountCode({
    "code" : "5_OFF_85-AAA111",
    "id" : int(time.time())
    })

discount_code_res = price_rule.add_discount_code(discount_code)
```

## Expected behavior

What do you think should happen?
I expect the discount code to be created or an error message stating what is incorrect.

## Actual behavior

What actually happens?
I get the below error which is unclear what is wrong with "price_rule_id".
<details>Traceback (most recent call last):
  File "/home/gerald/shopify/lib/python3.9/site-packages/pyactiveresource/connection.py", line 286, in _open
    http_response = self._handle_error(self._urlopen(request))
  File "/home/gerald/shopify/lib/python3.9/site-packages/pyactiveresource/connection.py", line 316, in _urlopen
    return urllib.request.urlopen(request, timeout=self.timeout)
  File "/usr/lib64/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib64/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib64/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gerald/shopify/lib/python3.9/site-packages/shopify/resources/price_rule.py", line 9, in add_discount_code
    resource = self.post("discount_codes", discount_code.encode())
  File "/home/gerald/shopify/lib/python3.9/site-packages/pyactiveresource/activeresource.py", line 1117, in _instance_post
    return self.klass.connection.post(url, self.klass.headers, body)
  File "/home/gerald/shopify/lib/python3.9/site-packages/pyactiveresource/connection.py", line 375, in post
    return self._open('POST', path, headers=headers, data=data)
  File "/home/gerald/shopify/lib/python3.9/site-packages/shopify/base.py", line 26, in _open
    self.response = super(ShopifyConnection, self)._open(*args, **kwargs)
  File "/home/gerald/shopify/lib/python3.9/site-packages/pyactiveresource/connection.py", line 288, in _open
    http_response = self._handle_error(err)
  File "/home/gerald/shopify/lib/python3.9/site-packages/pyactiveresource/connection.py", line 413, in _handle_error
    raise BadRequest(err)
pyactiveresource.connection.BadRequest: Response(code=400, body="b'{"errors":{"price_rule_id":"expected String to be a id"}}'", headers={'Date': 'Fri, 26 Mar 2021 00:16:24 GMT', ..., msg="Bad Request")</details>

## Steps to reproduce the problem

1. Run the snippet of code

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- `shopify_python_api` version: 8.3.0
- `pyactiveresource` version: 2.2.2
- Shopify API version used (e.g. `'2020-07'`): 2021-01

**Comment by mllemango** [comment]
Hey @nonfatalexec, since you're creating a new price rule, I don't believe `"price_rule_id" : 11111,` belongs in the body. Could you try removing that and see if the error still persists? The id should be taken from the response body instead.

**Comment by nonfatalexec** [comment]
Hi @mllemango,

I still get the `errors":{"price_rule_id":"expected String to be a id"}}'"` error. I originally tried without price_rule_id like you suggested. I added in price_rule_id because of the error message. I also tried with `"price_rule_id" : "11111"` and get the same error.

```python
price_rule = shopify.PriceRule.create({
    "title" : "5_OFF_85_000001",
    "target_type" : "line_item",
    "target_selection" : "entitled",
    "allocation_method" : "across",
    "value_type" : "fixed_amount",
    "value" : "-5",
    "once_per_customer" : True,
    "prerequisite_subtotal_range" : {"greater_than_or_equal_to" : "85.0"},
    "customer_selection" : "all",
    "starts_at" : datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    "ends_at" : (datetime.today() + timedelta(days=5)).strftime("%Y-%m-%d %H:%M:%S")
})
```
Error with above PriceRule.
<details>Traceback (most recent call last):
  File "/home/gerald/shopify/lib/python3.9/site-packages/pyactiveresource/connection.py", line 286, in _open
    http_response = self._handle_error(self._urlopen(request))
  File "/home/gerald/shopify/lib/python3.9/site-packages/pyactiveresource/connection.py", line 316, in _urlopen
    return urllib.request.urlopen(request, timeout=self.timeout)
  File "/usr/lib64/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib64/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib64/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gerald/shopify/scripts/./gelectronics_discount.py", line 69, in <module>
    discount_code_res = price_rule.add_discount_code(discount_code)
  File "/home/gerald/shopify/lib/python3.9/site-packages/shopify/resources/price_rule.py", line 9, in add_discount_code
    resource = self.post("discount_codes", discount_code.encode())
  File "/home/gerald/shopify/lib/python3.9/site-packages/pyactiveresource/activeresource.py", line 1117, in _instance_post
    return self.klass.connection.post(url, self.klass.headers, body)
  File "/home/gerald/shopify/lib/python3.9/site-packages/pyactiveresource/connection.py", line 375, in post
    return self._open('POST', path, headers=headers, data=data)
  File "/home/gerald/shopify/lib/python3.9/site-packages/shopify/base.py", line 26, in _open
    self.response = super(ShopifyConnection, self)._open(*args, **kwargs)
  File "/home/gerald/shopify/lib/python3.9/site-packages/pyactiveresource/connection.py", line 288, in _open
    http_response = self._handle_error(err)
  File "/home/gerald/shopify/lib/python3.9/site-packages/pyactiveresource/connection.py", line 413, in _handle_error
    raise BadRequest(err)
pyactiveresource.connection.BadRequest: Response(code=400, body="b'{"errors":{"price_rule_id":"expected String to be a id"}}'", ..., msg="Bad Request")
</details>

**Comment by mllemango** [comment]
Hey @nonfatalexec, looking at your code again I don't believe its your PriceRule.create() line that's the reason for this error. A few things I've noticed that will affect discount creation is
1. after a `price_rule = shopify.PriceRule.create()`, you'll need to run `price_rule.save()` for the API to actually make the POST request. The line `price_rule.add_discount_code` assumes that price_rule is already created. 
2. Since you've set "target_selection" : "entitled", I believe you'll need to provide an entitlement to the body (see the [docs](https://shopify.dev/docs/admin-api/rest/reference/discounts/pricerule/#create-2021-01) for example) for the price rule to be saved properly

Try again with these changes, hopefully that cleared things up!

**Comment by nonfatalexec** [comment]
Hi @mllemango, thanks for the suggestions. I realized I misunderstood entitlement and didn't need it, so I removed it. I tried the below and save() returned False. I'm also getting a "can't be blank" error validation error message.
```
price_rule = shopify.PriceRule.create({
    "title" : "5_OFF_85_000001",
    "target_type" : "line_item",
    "allocation_method" : "across",
    "value_type" : "fixed_amount",
    "value" : "-5",
    "once_per_customer" : True,
    "prerequisite_subtotal_range" : {"greater_than_or_equal_to" : "85.0"},
    "customer_selection" : "all",
    "starts_at" : datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    "ends_at" : (datetime.today() + timedelta(days=5)).strftime("%Y-%m-%d %H:%M:%S")
})

price_rule.save()
```
`False`
```
price_rule.errors.full_messages()
```
`["can't be blank"]`

**Comment by mllemango** [comment]
Try adding "target_selection" : "all" into the body instead of removing it

**Comment by nonfatalexec** [comment]
Hi @mllemango, thanks very much! This works.

**Comment by ChrisC0O** [comment]
Just spend a few hours debugging this. This seems to work for me.

```py
import shopify
from datetime import datetime, timezone
import time
from time import sleep

# Set up your Shopify API credentials
SHOP_URL = ""
API_KEY = ""
PASSWORD = ""

# Authenticate with the Shopify API
shopify.Session.setup(api_key=API_KEY, secret=PASSWORD)
session = shopify.Session(SHOP_URL, "2024-04", PASSWORD)
shopify.ShopifyResource.activate_session(session)



# Function to create a discount code on Shopify
def create_discount_codes(code_list):
  title = "10% AF PRISEN | 2025"
  print(f"Creating discount code: {title}")

  # Ensure that starts_at and ends_at are properly formatted as ISO 8601
  starts_at = datetime.now(timezone.utc).replace(tzinfo=None).isoformat()  # Remove the timezone info
  ends_at = datetime.now(timezone.utc).replace(year=2026,
                                               tzinfo=None).isoformat()  # Set year to 2026 and remove timezone info

  price_rule = shopify.PriceRule.create({
    "title": title,
    "target_type": "line_item",
    "target_selection": "all",
    "allocation_method": "across",
    "value_type": "percentage",
    "value": "-10",
    "once_per_customer": True,
    "usage_limit": 1,
    # "prerequisite_subtotal_range": {"greater_than_or_equal_to": "85.0"},
    "customer_selection": "all",
    "starts_at": starts_at,
    "ends_at": ends_at
  })

  print(f"Discount rule data: {price_rule.attributes}")

  try:
    price_rule.save()
    print(f"Created Price Rule with ID: {price_rule.id}")
  except Exception as e:
    print(f"Error saving discount rule: {e}")

  for code in code_list:

    # "Exceeded 2 calls per second for api client. Reduce request rates to resume uninterrupted service
    sleep(1.2)


    discount_code = shopify.DiscountCode({
      "code": code,
      "id": int(time.time()),
      "usage_count": 1,
      "price_rule_id": price_rule.id
    })

    discount_code_res = price_rule.add_discount_code(discount_code)

    print(f"Code {code} created")


    # Debug print the discount code object before saving
    print(f"Discount code object: {discount_code.attributes}")




with open("CUBONCODES_LIST.txt") as openfile:
  data = openfile.readlines()


scubed_list = []

for i in data:
  scubed_list.append(i.strip())

# Call the function to create discount codes
create_discount_codes(scubed_list)
```
