### ISSUE TITLE
Problem Adding Variant to new Product

### ISSUE THREAD

**Issue by michaelschem** [Shopify/shopify_python_api#523]
# Issue summary

When trying to create a new Product with multiple variants I get an error.

## Expected behavior

When I create a new product with multiple variants I should not get an error.

## Actual behavior

I get the following error:

<details>

Traceback (most recent call last):
  File "/Users/mschem/shopify_django_app/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/mschem/shopify_django_app/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/mschem/shopify_django_app/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/mschem/shopify_django_app/shopify_app/views.py", line 84, in add_product
    variant.save()
  File "/Users/mschem/shopify_django_app/venv/lib/python3.9/site-packages/shopify/resources/variant.py", line 18, in save
    self._prefix_options['product_id'] = self.product_id
  File "/Users/mschem/shopify_django_app/venv/lib/python3.9/site-packages/pyactiveresource/activeresource.py", line 917, in __getattr__
    raise AttributeError(name)

Exception Type: AttributeError at /shopify/add_product/
Exception Value: product_id

</details>

## Steps to reproduce the problem

```
product = shopify.Product()
product.title = "Test"
variant = shopify.Variant()
variant.title = "Small"
product.add_variant(variant)
```

---

## Checklist

- [x] I have described this issue in a way that is actionable (if possible)

**Comment by FaMux** [comment]
Try to call **product.save()** and afterwards check with **product.id** the ID of the new product. Than try to add a new product variant.
