### ISSUE TITLE
Orders.next_page() isn't working

### ISSUE THREAD

**Issue by kyletov** [Shopify/shopify_python_api#529]
# Issue summary

Write a short description of the issue here ↓

I'm retrieving orders using `orders = shopify.Order.find(limit=250, status='open', fulfillment_status='unshipped', order='created_at asc')`. I ran `orders.has_next_page()` to check if there's a next page (returns True) before running `orders.next_page()` to get the next page. But get an error instead

## Expected behavior

What do you think should happen?

It should return the next page of the initial order.find(...) configuration (i.e. the next 250 orders with the same filters)

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error
<details>TypeError: sequence item 1: expected str instance, NoneType found</details>

## Steps to reproduce the problem

1. Run `orders = shopify.Order.find(limit=250, status='open', fulfillment_status='unshipped', order='created_at asc')`
2. Run `orders.next_page()`
3. Should see error

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

---

## Checklist

- [✅] I have described this issue in a way that is actionable (if possible)

**Comment by kyletov** [comment]
Hey @paulomarg, pasting the stack trace here:

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/kyletov/.virtualenvs/fulfillment-service/lib/python3.7/site-packages/shopify/collection.py", line 92, in next_page
    return self.__fetch_page(self.next_page_url, no_cache)
  File "/Users/kyletov/.virtualenvs/fulfillment-service/lib/python3.7/site-packages/shopify/collection.py", line 95, in __fetch_page
    next = self.metadata["resource_class"].find(from_=url)
  File "/Users/kyletov/.virtualenvs/fulfillment-service/lib/python3.7/site-packages/shopify/base.py", line 199, in find
    collection = super(ShopifyResource, cls).find(id_=id_, from_=from_, **kwargs)
  File "/Users/kyletov/.virtualenvs/fulfillment-service/lib/python3.7/site-packages/pyactiveresource/activeresource.py", line 386, in find
    return cls._find_every(from_=from_, **kwargs)
  File "/Users/kyletov/.virtualenvs/fulfillment-service/lib/python3.7/site-packages/pyactiveresource/activeresource.py", line 525, in _find_every
    response = cls.connection.get(path, cls.headers)
  File "/Users/kyletov/.virtualenvs/fulfillment-service/lib/python3.7/site-packages/pyactiveresource/connection.py", line 329, in get
    return self._open('GET', path, headers=headers)
  File "/Users/kyletov/.virtualenvs/fulfillment-service/lib/python3.7/site-packages/shopify/base.py", line 26, in _open
    self.response = super(ShopifyConnection, self)._open(*args, **kwargs)
  File "/Users/kyletov/.virtualenvs/fulfillment-service/lib/python3.7/site-packages/pyactiveresource/connection.py", line 268, in _open
    six.iteritems(request.headers)])
  File "/Users/kyletov/.virtualenvs/fulfillment-service/lib/python3.7/site-packages/pyactiveresource/connection.py", line 267, in <listcomp>
    header_string = '\n'.join([':'.join((k, v)) for k, v in
TypeError: sequence item 1: expected str instance, NoneType found
```

**Comment by John-Doherty01** [comment]
@kyletov @paulomarg This issue looks possibly related to this issue raised: https://github.com/Shopify/shopify_python_api/issues/532
