### ISSUE TITLE
Webhooks no longer subscribing

### ISSUE THREAD

**Issue by John-Doherty01** [Shopify/shopify_python_api#532]
# Issue summary

Unable to create webhook via Python API. Error message below and steps to replicate

## Expected behavior

Webhook should create.

## Actual behavior

```
Traceback (most recent call last):
  File "/Users/johnd/workspace/trueforecast/api/trueforecast/api/shopify/SubscribeStoreWebhooks.py", line 32, in subscribe_all_webhooks
    webhook.create(
  File "/Users/johnd/opt/miniconda3/envs/trueforecast-api/lib/python3.8/site-packages/pyactiveresource/activeresource.py", line 450, in create
    resource.save()
  File "/Users/johnd/opt/miniconda3/envs/trueforecast-api/lib/python3.8/site-packages/pyactiveresource/activeresource.py", line 836, in save
    response = self.klass.connection.post(
  File "/Users/johnd/opt/miniconda3/envs/trueforecast-api/lib/python3.8/site-packages/pyactiveresource/connection.py", line 375, in post
    return self._open('POST', path, headers=headers, data=data)
  File "/Users/johnd/opt/miniconda3/envs/trueforecast-api/lib/python3.8/site-packages/shopify/base.py", line 26, in _open
    self.response = super(ShopifyConnection, self)._open(*args, **kwargs)
  File "/Users/johnd/opt/miniconda3/envs/trueforecast-api/lib/python3.8/site-packages/pyactiveresource/connection.py", line 267, in _open
    header_string = '\n'.join([':'.join((k, v)) for k, v in
  File "/Users/johnd/opt/miniconda3/envs/trueforecast-api/lib/python3.8/site-packages/pyactiveresource/connection.py", line 267, in <listcomp>
    header_string = '\n'.join([':'.join((k, v)) for k, v in
TypeError: sequence item 1: expected str instance, NoneType found
```

## Steps to reproduce the problem
Pip version `ShopifyAPI==8.4.2`
API version `2021-07`

```
        shopify.ShopifyResource.clear_session()
        session_context = self.store.shopify_session_contents
        with shopify.Session.temp(session_context.get('url'), session_context.get('api_version'),
                                  session_context.get('token')):
            webhook = shopify.Webhook()
            webhook.create(
                {
                    'topic': 'inventory_levels/update',
                    'address': 'SOME_URL_HERE',
                    'format': 'json'
                }
            )
```

---

## Checklist

- [X] I have described this issue in a way that is actionable (if possible)

**Comment by John-Doherty01** [comment]
Possible fix of manually setting headers
```
shopify.ShopifyResource.set_headers(
    {'User-Agent': 'ShopifyPythonAPI/8.4.2 Python/3.8.8',
     'X-Shopify-Access-Token': session_context.get('token')}
)

```

**Comment by John-Doherty01** [comment]
Figured out cause of issue I had a `with` nested in a `with` and it was causing the session to clear before webhook create was called which mean't `X-shopify-access-token` was None. Error reporting could be improved to make it clearer that it is None rather than displaying the above error message.
