### ISSUE TITLE
    raise VersionNotFoundError

### ISSUE THREAD

**Issue by KhoaDauTay** [Shopify/shopify_python_api#579]
# Issue summary
I try connect myshopify admin api with GraphQL but version is error.

## Expected behavior

Version Error
```
KeyError: '2022-04'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/khoa/.pyenv/versions/dogo-fastapi/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/khoa/.pyenv/versions/dogo-fastapi/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/khoa/.pyenv/versions/dogo-fastapi/lib/python3.9/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/home/khoa/.pyenv/versions/dogo-fastapi/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/khoa/.pyenv/versions/dogo-fastapi/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/home/khoa/.pyenv/versions/dogo-fastapi/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/khoa/.pyenv/versions/dogo-fastapi/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/khoa/.pyenv/versions/dogo-fastapi/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/home/khoa/.pyenv/versions/dogo-fastapi/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/khoa/.pyenv/versions/dogo-fastapi/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/khoa/.pyenv/versions/dogo-fastapi/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/khoa/.pyenv/versions/dogo-fastapi/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/home/khoa/.pyenv/versions/dogo-fastapi/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/home/khoa/.pyenv/versions/dogo-fastapi/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/home/khoa/.pyenv/versions/dogo-fastapi/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/home/khoa/.pyenv/versions/dogo-fastapi/lib/python3.9/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/khoa/.pyenv/versions/dogo-fastapi/lib/python3.9/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/khoa/.pyenv/versions/dogo-fastapi/lib/python3.9/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/home/khoa/.pyenv/versions/dogo-fastapi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/home/khoa/.pyenv/versions/dogo-fastapi/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/home/khoa/Documents/dogo/dogo-fastapi/./app/main.py", line 54, in get_order
    session = shopify.Session(
  File "/home/khoa/.pyenv/versions/dogo-fastapi/lib/python3.9/site-packages/shopify/session.py", line 52, in __init__
    self.version = ApiVersion.coerce_to_version(version)
  File "/home/khoa/.pyenv/versions/dogo-fastapi/lib/python3.9/site-packages/shopify/api_version.py", line 20, in coerce_to_version
    raise VersionNotFoundError
shopify.api_version.VersionNotFoundError

```

Debug version is str: '2022-04' but not found

## Actual behavior

My setup
```
    shop_setting = ShopifySetting()

    shopify.Session.setup(
        api_key=shop_setting.api_key,
        secret=shop_setting.api_secret
    )
    session = shopify.Session(
        shop_setting.shopify_url,
        shop_setting.api_version,
        shop_setting.access_token
    )
    shopify.ShopifyResource.activate_session(session)
    result = shopify.GraphQL().execute('{ shop { name id } }')
```

# Debug version show

![image](https://user-images.githubusercontent.com/54214642/161941916-1b93a3c5-f4e1-42c6-9865-98df912cccd2.png)

**Comment by quanld1502** [comment]
@mllemango It works with new version.
