### ISSUE TITLE
KeyError: '2020-10', shopify.api_version.VersionNotFoundError

### ISSUE THREAD

**Issue by y3** [Shopify/shopify_python_api#598]
Hi,

I am trying to follow the 'Get Started' code however I am getting:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\shopify\api_version.py", line 18, in coerce_to_version
    return cls.versions[version]
KeyError: '2020-10'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Code\Correction Label Maker\main.py", line 10, in <module>
    newSession = shopify.Session(shop_url, api_version)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\shopify\session.py", line 52, in __init__
    self.version = ApiVersion.coerce_to_version(version)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\shopify\api_version.py", line 20, in coerce_to_version
    raise VersionNotFoundError
shopify.api_version.VersionNotFoundError

**Comment by y3** [comment]
nevermind, i now realise my mistake lol sorry
