### ISSUE TITLE
After session connection, commands not working

### ISSUE THREAD

**Issue by pama1999** [Shopify/shopify_python_api#636]
## Short description
After connecting to the session, I seem to recieve an error no matter what I run. GraphQL Execute also wont work

```terminal
['/home/parham/ShopifyGraphQl', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/parham/ShopifyGraphQl/venv/lib/python3.10/site-packages']
/home/parham/ShopifyGraphQl/venv/bin/python
3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0]
Traceback (most recent call last):
  File "/home/parham/ShopifyGraphQl/main.py", line 12, in <module>
    shop = shopify.Shop.current()
  File "/home/parham/ShopifyGraphQl/venv/lib/python3.10/site-packages/shopify/resources/shop.py", line 9, in current
    return cls.find_one(cls.site + "/shop." + cls.format.extension)
  File "/home/parham/ShopifyGraphQl/venv/lib/python3.10/site-packages/pyactiveresource/activeresource.py", line 420, in find_one
    return cls._find_one(from_, kwargs)
  File "/home/parham/ShopifyGraphQl/venv/lib/python3.10/site-packages/pyactiveresource/activeresource.py", line 504, in _find_one
    return cls._build_object(cls.connection.get_formatted(path, cls.headers))
  File "/home/parham/ShopifyGraphQl/venv/lib/python3.10/site-packages/pyactiveresource/connection.py", line 340, in get_formatted
    return self.format.decode(self.get(path, headers).body)
  File "/home/parham/ShopifyGraphQl/venv/lib/python3.10/site-packages/pyactiveresource/connection.py", line 329, in get
    return self._open('GET', path, headers=headers)
  File "/home/parham/ShopifyGraphQl/venv/lib/python3.10/site-packages/shopify/base.py", line 23, in _open
    self.response = super(ShopifyConnection, self)._open(*args, **kwargs)
  File "/home/parham/ShopifyGraphQl/venv/lib/python3.10/site-packages/pyactiveresource/connection.py", line 267, in _open
    header_string = '\n'.join([':'.join((k, v)) for k, v in
  File "/home/parham/ShopifyGraphQl/venv/lib/python3.10/site-packages/pyactiveresource/connection.py", line 267, in <listcomp>
    header_string = '\n'.join([':'.join((k, v)) for k, v in
TypeError: sequence item 1: expected str instance, NoneType found
```

## Steps to reproduce the problem

1. virtualenv venv
2. pip install shopifyAPI
3. run main.py

## main.py
```python
import shopify
import os
import sys

print(sys.path)
print(sys.executable)
print(sys.version)


session = shopify.Session("shopname.com", version="2023-01", token=os.getenv("access_token"))
shopify.ShopifyResource.activate_session(session)
shop = shopify.Shop.current()
print(shop)
```

**Comment by pama1999** [comment]
the error was not shopify related

**Comment by cristoper** [comment]
I'm not the original poster, but this is the error you get if your session is not active or if you don't set the store name or api token when activating the session.
