### ISSUE TITLE
Memory increases consistently when fetching orders in a loop

### ISSUE THREAD

**Issue by bhr** [Shopify/shopify_python_api#658]
# Issue summary

We've seen memory increase consistently when processing orders using the paginated queries. 

## Expected behavior

Memory should remain constant

## Actual behavior

Memory increases after every iteration of fetching `next_orders()` on an orders query.

## Steps to reproduce the problem

1. Process orders for a store

## Reduced test case

```python
        import tracemalloc
        import profiler
        import gc
        import shopify

        tracemalloc.start(10)
        current_orders_page = shopify.Order.find(status="any")
        iteration = 0
        while True:
            # process orders on page
            logger.debug(f"Processing {len(current_orders_page)} orders on current page")

            gc.collect()
            profiler.snapshot()

            # proceed to next page
            if current_orders_page.has_next_page():
                iteration += 1
                next_products_page = current_orders_page.next_page()
                current_orders_page = next_products_page
            else:
                profiler.display_stats()
                profiler.compare()
                profiler.print_trace()
                break

```

FYI, our profiler.py file
```python
import tracemalloc

# list to store memory snapshots
snaps = []


def snapshot():
    snaps.append(tracemalloc.take_snapshot())


def display_stats():
    stats = snaps[0].statistics("filename")
    print("\n*** top 5 stats grouped by filename ***")
    for s in stats[:5]:
        print(s)


def compare():
    first = snaps[0]
    for snapshot in snaps[1:]:
        stats = snapshot.compare_to(first, "lineno")
        print("\n*** top 10 stats ***")
        for s in stats[:10]:
            print(s)


def print_trace():
    # pick the last saved snapshot, filter noise
    snapshot = snaps[-1].filter_traces(
        (
            tracemalloc.Filter(False, "<frozen importlib._bootstrap>"),
            tracemalloc.Filter(False, "<frozen importlib._bootstrap_external>"),
            tracemalloc.Filter(False, "<unknown>"),
        )
    )
    largest = snapshot.statistics("traceback")[0]

    print(f"\n*** Trace for largest memory block - ({largest.count} blocks, {largest.size/1024} Kb) ***")
    for l in largest.traceback.format():
        print(l)

```

---

## Checklist

- [X] I have described this issue in a way that is actionable (if possible)

## Additional logs

`tracemalloc` shows `pyactiveresource` growing consistently with every iteration

```
*** top 5 stats grouped by filename ***
/usr/local/lib/python3.9/threading.py:0: size=535 KiB, count=5811, average=94 B
/root/.local/lib/python3.9/site-packages/google/cloud/firestore_v1/_helpers.py:0: size=141 KiB, count=2126, average=68 B
/root/.vscode-server/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_trace_dispatch_regular.py:0: size=104 KiB, count=1846, average=58 B
/workspaces/vestico/product-order-integration/common/model/product.py:0: size=86.7 KiB, count=1387, average=64 B
/root/.vscode-server/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_additional_thread_info_regular.py:0: size=79.1 KiB, count=682, average=119 B

*** top 10 stats ***
/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py:203: size=6391 KiB (+6391 KiB), count=31092 (+31092), average=210 B
/usr/local/lib/python3.9/json/decoder.py:353: size=595 KiB (+595 KiB), count=10948 (+10948), average=56 B
/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py:928: size=435 KiB (+435 KiB), count=8566 (+8566), average=52 B
/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py:35: size=435 KiB (+435 KiB), count=8566 (+8566), average=52 B
/usr/local/lib/python3.9/http/client.py:582: size=415 KiB (+415 KiB), count=1 (+1), average=415 KiB
/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py:983: size=348 KiB (+348 KiB), count=368 (+368), average=969 B
/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py:358: size=268 KiB (+268 KiB), count=4283 (+4283), average=64 B
/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py:36: size=268 KiB (+268 KiB), count=4283 (+4283), average=64 B
/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py:362: size=264 KiB (+264 KiB), count=4232 (+4232), average=64 B
/usr/local/lib/python3.9/re.py:210: size=234 KiB (+234 KiB), count=3724 (+3724), average=64 B

*** top 10 stats ***
/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py:203: size=12.0 MiB (+12.0 MiB), count=60076 (+60076), average=210 B
/usr/local/lib/python3.9/json/decoder.py:353: size=1139 KiB (+1139 KiB), count=20979 (+20979), average=56 B
/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py:928: size=840 KiB (+840 KiB), count=16542 (+16542), average=52 B
/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py:35: size=840 KiB (+840 KiB), count=16542 (+16542), average=52 B
/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py:983: size=663 KiB (+663 KiB), count=702 (+702), average=968 B
/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py:358: size=517 KiB (+517 KiB), count=8271 (+8271), average=64 B
/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py:36: size=517 KiB (+517 KiB), count=8271 (+8271), average=64 B
/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py:362: size=510 KiB (+510 KiB), count=8165 (+8165), average=64 B
/usr/local/lib/python3.9/re.py:210: size=453 KiB (+453 KiB), count=7198 (+7198), average=64 B
/root/.local/lib/python3.9/site-packages/pyactiveresource/util.py:210: size=446 KiB (+446 KiB), count=7198 (+7198), average=63 B

*** top 10 stats ***
/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py:203: size=17.8 MiB (+17.8 MiB), count=89106 (+89106), average=210 B
/usr/local/lib/python3.9/json/decoder.py:353: size=1697 KiB (+1697 KiB), count=31222 (+31222), average=56 B
/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py:928: size=1247 KiB (+1247 KiB), count=24552 (+24552), average=52 B
/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py:35: size=1247 KiB (+1247 KiB), count=24552 (+24552), average=52 B
/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py:983: size=989 KiB (+989 KiB), count=1041 (+1041), average=973 B
/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py:358: size=767 KiB (+767 KiB), count=12276 (+12276), average=64 B
/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py:36: size=767 KiB (+767 KiB), count=12276 (+12276), average=64 B
/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py:362: size=758 KiB (+758 KiB), count=12120 (+12120), average=64 B
/usr/local/lib/python3.9/re.py:210: size=672 KiB (+672 KiB), count=10679 (+10679), average=64 B
/root/.local/lib/python3.9/site-packages/pyactiveresource/util.py:210: size=662 KiB (+662 KiB), count=10679 (+10679), average=63 B

*** top 10 stats ***
/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py:203: size=23.8 MiB (+23.8 MiB), count=119109 (+119109), average=210 B
/usr/local/lib/python3.9/json/decoder.py:353: size=2325 KiB (+2325 KiB), count=42647 (+42647), average=56 B
/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py:928: size=1675 KiB (+1675 KiB), count=32980 (+32980), average=52 B
/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py:35: size=1675 KiB (+1675 KiB), count=32980 (+32980), average=52 B
/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py:983: size=1397 KiB (+1397 KiB), count=1460 (+1460), average=980 B
/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py:358: size=1031 KiB (+1031 KiB), count=16490 (+16490), average=64 B
/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py:36: size=1031 KiB (+1031 KiB), count=16490 (+16490), average=64 B
/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py:362: size=1018 KiB (+1018 KiB), count=16284 (+16284), average=64 B
/usr/local/lib/python3.9/re.py:210: size=899 KiB (+899 KiB), count=14281 (+14281), average=64 B
/root/.local/lib/python3.9/site-packages/pyactiveresource/util.py:210: size=885 KiB (+885 KiB), count=14281 (+14281), average=63 B

*** top 10 stats ***
/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py:203: size=29.0 MiB (+29.0 MiB), count=145281 (+145281), average=209 B
/usr/local/lib/python3.9/json/decoder.py:353: size=2832 KiB (+2832 KiB), count=51998 (+51998), average=56 B
/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py:928: size=2044 KiB (+2044 KiB), count=40256 (+40256), average=52 B
/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py:35: size=2044 KiB (+2044 KiB), count=40256 (+40256), average=52 B
/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py:983: size=1700 KiB (+1700 KiB), count=1761 (+1761), average=989 B
/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py:358: size=1258 KiB (+1258 KiB), count=20128 (+20128), average=64 B
/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py:36: size=1258 KiB (+1258 KiB), count=20128 (+20128), average=64 B
/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py:362: size=1242 KiB (+1242 KiB), count=19870 (+19870), average=64 B
/usr/local/lib/python3.9/re.py:210: size=1098 KiB (+1098 KiB), count=17431 (+17431), average=64 B
/root/.local/lib/python3.9/site-packages/pyactiveresource/util.py:210: size=1081 KiB (+1081 KiB), count=17431 (+17431), average=63 B

*** Trace for largest memory block - (51763 blocks, 10255.1875 Kb) ***
  File "/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py", line 363
    self._update(attributes)
  File "/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py", line 977
    attr.append(klass(child))
  File "/root/.local/lib/python3.9/site-packages/shopify/base.py", line 166
    return super(ShopifyResource, self).__init__(attributes, prefix_options)
  File "/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py", line 363
    self._update(attributes)
  File "/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py", line 969
    attr = klass(value)
  File "/root/.local/lib/python3.9/site-packages/shopify/base.py", line 166
    return super(ShopifyResource, self).__init__(attributes, prefix_options)
  File "/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py", line 363
    self._update(attributes)
  File "/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py", line 968
    klass = self._find_class_for(key)
  File "/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py", line 1045
    return type(str(class_name), (cls,), {'__module__': cls.__module__})
  File "/root/.local/lib/python3.9/site-packages/pyactiveresource/activeresource.py", line 203
    klass = type.__new__(mcs, name, bases, new_attrs)
^C2023-06-01T17:12:30+0000.628: INFO     – Cleared session
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/.vscode-server/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/root/.vscode-server/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/root/.vscode-server/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 317, in run_module
    run_module_as_main(options.target, alter_argv=True)
  File "/root/.vscode-server/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 238, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/.vscode-server/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/workspaces/vestico/product-order-integration/integration/__main__.py", line 65, in <module>
    controller.ingest()
  File "/workspaces/vestico/product-order-integration/integration/ingest.py", line 51, in ingest
    self.ingest_provider(provider)
  File "/workspaces/vestico/product-order-integration/integration/ingest.py", line 62, in ingest_provider
    self.run_ingest(provider_data)
  File "/workspaces/vestico/product-order-integration/integration/orders/manager.py", line 16, in run_ingest
    controller.ingest()
  File "/workspaces/vestico/product-order-integration/integration/abstractingest.py", line 26, in ingest
    output = self.run_ingest()
  File "/workspaces/vestico/product-order-integration/integration/orders/controller.py", line 107, in run_ingest
    data_fetcher.fetch_data(map_data_callback, schedule_batch_callback)
  File "/workspaces/vestico/product-order-integration/integration/fetchers/shopify/orderfetcher.py", line 83, in fetch_data
    break
  File "/workspaces/vestico/product-order-integration/integration/fetchers/shopify/orderfetcher.py", line 83, in fetch_data
    break
  File "/root/.vscode-server/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py", line 988, in trace_dispatch
    self.do_wait_suspend(thread, frame, event, arg)
  File "/root/.vscode-server/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py", line 165, in do_wait_suspend
    self._args[0].do_wait_suspend(*args, **kwargs)
  File "/root/.vscode-server/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2070, in do_wait_suspend
    keep_suspended = self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread, frames_tracker)
  File "/root/.vscode-server/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2106, in _do_wait_suspend
    time.sleep(0.01)
```

**Comment by bhr** [comment]
@shopify-admins Can you confirm this issue? Any workarounds?

**Comment by bhr** [comment]
@ivan-ivkovic That seems to resolve the issue, thanks so much for sharing!
